[package]
name = "rocket-tracing-fairing-example"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rocket = { version = "0.5.0-rc.1", features = ["json"] }
serde = {version="1.0.133", features=["derive"]}
serde_json = "1.0.74"
tracing = "0.1.29"
uuid = {version="0.8.2", features = ["v4"]}
